### ISSUE TITLE
Bullets are black

### ISSUE THREAD

**Issue by l29ah** [laochailan/taisei#39]
On master on an intel video card with shaders disabled.

**Comment by nexAkari** [comment]
>with shaders disabled

That's the problem. This game uses shaders to color them.

**Comment by l29ah** [comment]
On Tue, Dec 15, 2015 at 06:53:15PM -0800, Andrew Alexeyew wrote:
> >with shaders disabled
> 
> That's the problem. This game uses shaders to color them.

Uhh, okay. In fact i didn't expect a touhou game to fail to perform on a 5yo laptop (and with disabled shaders it's quite slow).

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by lachs0r** [comment]
Blame Intel for only producing decent-ish integrated graphics after AMD’s low-end APUs blew everything they had out of the water (so, starting with HD 4000 series) and never coming up with decent drivers.

FWIW, this runs perfectly fine on an 11yo laptop with entry-level ATI graphics, shaders enabled (r300g driver).
