### ISSUE TITLE
Desyncing replays, tsrand, etc.

### ISSUE THREAD

**Issue by Akaricchi** [laochailan/taisei#48]
I'm still bitter about this issue and probably going to investigate it again sometime soon. I'm not sure if this is caused by incorrect usage of the tsrand functions somewhere, but I believe it's highly probable and should be tripple-checked first. At very least, the naming of those functions should definitely be revised -- what the fuck does an ```anfrand()``` do?

If you have any thoughts about replays and/or RNG, you're more than welcome to discuss them here.

**Comment by laochailan** [comment]
My guess is *n* for *normal*, *f* for *float* and *a* for *a bad abbreviation*.
Now that I had my share of statistics, I understand why aiju was so mad when we only checked the mean of those functions. I may plot a histogram of them for once :smile:

**Comment by Akaricchi** [comment]
That'd be welcome, though I don't think the quality of the RNG itself would be a cause for desyncing, for as long as it generates consistent sequences on all platforms.

As for floats, while it might not fix anything I think we should at least use double instead of float consistently. It's all over the place right now. You can never tell when an implicit conversion occurs. Maybe we'll even abandon them for fixed-point arithmentic eventually, but that sounds a bit scary right now, considering the amount of rewriting involved...

Another thing is that we store some initial player state in the replay, and some of it are floats (the coordinates). The replay file structure is stupid and text-based, and the textual representation of those floats may just not be accurate enough. I think I'll look into going back to a binary format for it again, once the SDL2 branch is merged. There's a supposedly portable API for raw I/O that I could use. It always bothered me how it's text based anyway, even though virtually all of the data in there are numbers.

**Comment by laochailan** [comment]
Yes of course it wouldn’t be at heart of the desync issues, but I’m curious if those are really behaving like they should. (and I have an urge to apply statistics)

Switching to double might be okay, but in the end everything is going to be implicitly cast to float by all the OpenGL calls.

Fixed point arithmetic seems like a bad idea. What would be the merit? Just to get replays cross platform? That can’t be a solution. Think about the amount of lookup tables and things you would need to get right just for a fixed point carg().
If things really start getting inaccurate, we can think about saving the absolute position or something or introducing some subtle rounding in the collision checks that is not noticeable to the player but larger than round-off error/machine differences.

I think we should do neither that nor the float to double thing before we are sure that’s what is causing it.

But switching to binary would be very nice :smile:

**Comment by Akaricchi** [comment]
> Yes of course it wouldn’t be at heart of the desync issues, but I’m curious if those are really behaving like they should. (and I have an urge to apply statistics)

Go ahead then, I'm interested in the results too.

> Switching to double might be okay, but in the end everything is going to be implicitly cast to float by all the OpenGL calls.

Not literally everything. Those casts are acceptable since we know for sure they won't interfere with the game state in any way.

Yeah, I went a bit too far with the fixed-point. I like your rounding idea.

**Comment by Akaricchi** [comment]
I've pushed a `replaysagain` branch with an initial implementation of the new format. For the record, I think there is a desync bug in the stage 6 boss fight. Not sure exactly where. But it seems to desync even on the same system.

**Comment by laochailan** [comment]
![hist](https://cloud.githubusercontent.com/assets/239670/22624843/e899bb8e-eb87-11e6-8812-47dcd0a6c661.png)
It seems to be alright. In fact there already was code to export random numbers so we might have done a test like that before.

**Comment by Akaricchi** [comment]
Let's move the discussion to #50.
