### ISSUE TITLE
Gamepad input is broken in restricted axes mode

### ISSUE THREAD

**Issue by lachs0r** [laochailan/taisei#55]
Right now, gamepad input easily gets stuck in a direction when using analog axes.

**Comment by Akaricchi** [comment]
Please test d9611b0831f69a591c1a74a872739d1c93472875 and see if that fixes anything for you. You might also want to increase the deadzone a bit if you're getting noisy inputs.

**Comment by Akaricchi** [comment]
I'm closing this, seems like nobody has been able to reproduce this since the gamepad code rewrite.
