### ISSUE TITLE
Switching from ALUT to SDL_mixer

### ISSUE THREAD

**Issue by lachs0r** [laochailan/taisei#56]
This is probably better because SDL_mixer implements some features we could use, and ALUT/OpenAL has a lot of features we don’t really need (like 3D positional audio). Also, cross compiling those libraries with static linking is kind of a pain, and freealut does not appear to be readily available everywhere.

**Comment by laochailan** [comment]
I agree.

**Comment by makise-homura** [comment]
I've even started to do such migration in my fork a couple days before (but still there are a little mess with BGM pausing/continuing, but I hope to resolve every problem there). Maybe I'll complete this work till this weekend, on in beginning of next week...

**Comment by Akaricchi** [comment]
@makise-homura could you make a pull request please? Even if it's not finished yet. It's easier to keep track of progress that way.

**Comment by makise-homura** [comment]
Ok, I'll do it now (by the way, it is not even runned for a test, only built).

**Comment by Akaricchi** [comment]
Closing this since there's #59 now.
